-- run_once(prg,arg_string,pname,screen)
--run_once("skypeforlinux")
run_once("dropbox")
run_once("nm-applet")
--run_once("jetbrains-toolbox --minimize")
--run_once("/home/id/.local/share/JetBrains/Toolbox/bin/jetbrains-toolbox --minimize")
--run_once("empathy")
--run_once("pidgin")
run_once("slack")
--run_once("telegram-desktop")
run_once("thunderbird")
-- run_once("firefox")
-- run_once("google-chrome-stable")
--run_once("gnome-commander")
--run_once("teamviewer12")
--run_once("pac")
--run_once("subl")
--run_once("sublime_text")
run_once("shutter --min_at_startup")
run_once("remmina -i")
run_once("goldendict")
--run_once("clipit")
run_once("xscreensaver -no-splash")
--run_once("yakyak")


